[tasks.test]
cmd = "pytest"

[tasks.test-multienv]
cmd = "tox"

[tasks.lint]
sequence = [
  { cmd = "ruff check $path" },
  { cmd = "mypy $path" },
]
args = [
  { name = "path", positional = true, default = "" }
]

[tasks.docs]
script = "src.helpers.docs_cli"
