.SH EXAMPLES
.P
Produce "file.pdf" in the current directory:
.IP
dpsprep /wherever/file.djvu
.P
Produce "output.pdf" with reduced image quality and aggressive PDF image optimizations:
.IP
dpsprep --quality=30 -O3 input.djvu output.pdf
.P
Produce an output file using a large pool of workers:
.IP
dpsprep --pool=16 input.djvu
.P
Force bitonal images:
.IP
dpsprep --mode bitonal input.djvu
.P
Produce an output file by disregarding the text layer and running OCRmyPDF instead:
.IP
dpsprep --socr rus,eng,grc input.djvu
.P
Simply disregard the text layer without OCR:
.IP
dpsprep --no-text input.djvu
