name: Build docs

on:
  push:
    tags:
      - '**'

jobs:
  docs:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Install prerequisites on Ubuntu
      run: |
        sudo apt update
        sudo apt install --yes libdjvulibre21 libdjvulibre-dev

    - uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: uv sync

    - name: Build docs
      run: |
        uv run poe build-docs
        mkdir .github/wiki
        cp --recursive docs/*.md docs/screenshots .github/wiki

    - name: Upload to wiki
      uses: spenserblack/actions-wiki@v0.3.0
