name: Build docs

on:
  push:
    branches:
      - 'master'

jobs:
  docs:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - name: Install prerequisites on Ubuntu
      run: |
        sudo apt update
        sudo apt install --yes libdjvulibre21 libdjvulibre-dev groff

    - name: Setup uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync --frozen --group docs --no-default-groups

    - name: Build docs
      run: |
        uv run --no-sync poe build-docs
        mkdir .github/wiki
        cp --recursive docs/*.md docs/screenshots .github/wiki

    - name: Upload to wiki
      uses: spenserblack/actions-wiki@v0.3.0
