name: Run tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
          submodules: true

    - name: Install prerequisites on Ubuntu
      if: matrix.os == 'ubuntu-24.04'
      run: |
        sudo apt update
        sudo apt install --yes libdjvulibre21 libdjvulibre-dev

    - name: Install prerequisites on macOS
      if: matrix.os == 'macos-14'
      run: brew install djvulibre libtiff

    # - name: Install prerequisites on Windows
    #   if: matrix.os == 'windows-2022'
    #   run: |
    #     choco install djvu-libre
    #     vcpkg install tiff

    - uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: uv sync --all-extras

    - name: Lint
      run: make lint

    - name: Test
      run: make test
