name: Run tests

on:
  push:
    branches:
      - 'master'

  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-slim
            python: 3.11
          - os: ubuntu-slim
            python: 3.12
          - os: ubuntu-slim
            python: 3.13
          - os: ubuntu-slim
            python: 3.14
          - os: macos-26
            python: 3.14

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Install prerequisites on Ubuntu
      if: matrix.os == 'ubuntu-slim'
      run: |
        sudo apt update
        sudo apt install --yes libdjvulibre21 libdjvulibre-dev

    - name: Install prerequisites on macOS
      if: matrix.os == 'macos-26'
      run: brew install djvulibre

    # - name: Install prerequisites on Windows
    #   if: matrix.os == 'windows-2022'
    #   run: |
    #     choco install djvu-libre
    #     vcpkg install tiff

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: uv sync --frozen --group lint --group typing --group test --no-default-groups

    - name: Lint
      run: uv run --no-sync ruff check

    - name: Typing
      run: uv run --no-sync mypy

    - name: Test
      run: uv run --no-sync pytest
